### ISSUE TITLE
Disassemble local functions?

### ISSUE THREAD

**Issue by lifepillar** [lacygoill/vim9asm#2]
Thanks for this, it's really useful! Is it possible to disassemble script-local functions? I hoped that this would work:

```vim
def  F()
# ...
enddef

defcompile

Disassemble F
```

but that results in `E1061: Cannot find function F`. Note that the built-in `disassemble F` would print the instructions to the command line.

**Comment by lacygoill** [comment]
> Is it possible to disassemble script-local functions?

Yes, it works on the command-line; but a wildcard needs to be prefixed in front of the function name, then Tab must be pressed so that Vim expands it.  For example:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func()
            echo 'test'
        enddef
        packadd vim9asm
        feedkeys(":Disa *Func(\t\r", 't')
    EOF
    )

> Note that the built-in disassemble F would print the instructions to the command line.

I think the issue – when executed from a script rather than interactively – is that the script context in which `:Disa` is run does not match the one where it's defined.

I've just pushed a commit which tries to address the issue; it seems to work in a special case I worked on, but I don't know how reliable it will be in the general case.

**Comment by lifepillar** [comment]
>Yes, it works on the command-line; but a wildcard needs to be prefixed in front of the function name

Ah ok, I was missing the wildcard.

>I think the issue – when executed from a script rather than interactively – is that the script context in which :Disa is run does not match the one where it's defined.

Executing from the command-line is what I was trying to do. It didn't occurred to me that executing it from a script would be any different. Anyway…

>I've just pushed a commit which tries to address the issue

…that appears to work fine. Thanks!
