### ISSUE TITLE
Disassemble functions generated by higher-level functions

### ISSUE THREAD

**Issue by lifepillar** [lacygoill/vim9asm#5]
Consider this script:

```vim
vim9script

def Map(F: func(any): any): func(any): any
  return (x) => {
    return F(x)
  }
enddef

const G = Map((s) => str2nr(s))
```

Is it possible to get a disassembly of `G`?

**Edit:** Fix typo

**Comment by lacygoill** [comment]
It's not possible to disassemble it from the command-line, not even with the builtin `:disassemble`; because `G` is a script-local variable; but on the command-line we're no longer in a script; so `G` is not accessible.

It is possible to disassemble `G` *from its script* (not from the command-line) with `:disassemble`:
```vim
vim9script
def Map(F: func(any): any): func(any): any
  return (x) => {
    return F(x)
  }
enddef
const G = Map((s) => str2nr(s))
disassemble G
```
    <lambda>2
        return F(x)
       0 LOAD arg[-1]
       1 LOADOUTER level 1 $-7
       2 PCALL (argc 1)
       3 RETURN

But it's not possible with `:Disassemble`:
```vim
vim9script
def Map(F: func(any): any): func(any): any
  return (x) => {
    return F(x)
  }
enddef
const G = Map((s) => str2nr(s))
Disassemble G
```
    Vim(disassemble):E1061: Cannot find function G

That's because a user command (such as `:Disassemble`) is run in the context of the script where it's defined; not the script from which it's called.  So `:Disassemble` cannot access/evaluate `G`.

As a simple workaround, maybe you could create a copy of `G` in the global namespace:
```vim
vim9script
def Map(F: func(any): any): func(any): any
  return (x) => {
    return F(x)
  }
enddef
const G = Map((s) => str2nr(s))
g:G = G
Disassemble g:G
```
Then you could disassemble the function from its script, as well as from the command-line.

**Comment by lifepillar** [comment]
Great explanation! Thanks!
